// AUTOGENERATED by bondrewd\tools\asdl++\asdl_cpp.py on 2023-03-08 12:24:21
// DO NOT EDIT

#pragma once

#include <bondrewd/internal/common.hpp>
#include <bondrewd/ast/ast.hpp>


namespace bondrewd::ast::nodes {


class cartridge : public _AST<Cartridge> {
public:
    #pragma region Constructors
    cartridge(auto &&value)
        : _AST(std::forward<decltype(value)>(value)) {}
    #pragma endregion Constructors
    
    #pragma region Service constructors
    cartridge(const cartridge &) = delete;
    cartridge(cartridge &&) = default;
    cartridge &operator=(const cartridge &) = delete;
    cartridge &operator=(cartridge &&) = default;
    #pragma endregion Service constructors

    #pragma region Destructor
    ~cartridge() = default;
    #pragma endregion Destructor

    #pragma region Attributes
    
    #pragma endregion Attributes

    #pragma region Extras
    
    #pragma endregion Extras
};


class Cartridge : _ConcreteASTNode {
public:
    #pragma region Fields
    sequence<stmt> body;
    #pragma endregion Fields

    #pragma region Constructors
    Cartridge(sequence<stmt> body) :
        body{std::move(body)} {}
    #pragma endregion Constructors
    
    #pragma region Service constructors
    Cartridge(const Cartridge &) = delete;
    Cartridge(Cartridge &&) = default;
    Cartridge &operator=(const Cartridge &) = delete;
    Cartridge &operator=(Cartridge &&) = default;
    #pragma endregion Service constructors

    #pragma region Uniform fields access
    /**
     * Returns a tuple of references to all fields.
     * Note that the tuple may include sequences (std::vector) and optional fields (null unique_ptr's).
     */
    auto get_fields_tuple() {
        return std::tie(body);
    }
    #pragma endregion Uniform fields access

    #pragma region Extras
    
    #pragma endregion Extras
};


class stmt : public _AST<VarDef, Impl, Assign, Expr, Pass> {
public:
    #pragma region Constructors
    stmt(auto &&value)
        : _AST(std::forward<decltype(value)>(value)) {}
    #pragma endregion Constructors
    
    #pragma region Service constructors
    stmt(const stmt &) = delete;
    stmt(stmt &&) = default;
    stmt &operator=(const stmt &) = delete;
    stmt &operator=(stmt &&) = default;
    #pragma endregion Service constructors

    #pragma region Destructor
    ~stmt() = default;
    #pragma endregion Destructor

    #pragma region Attributes
    
    #pragma endregion Attributes

    #pragma region Extras
    
    #pragma endregion Extras
};


class VarDef : _ConcreteASTNode {
public:
    #pragma region Fields
    field<identifier> name;
    maybe<expr> type;
    maybe<expr> value;
    field<bool> mut;
    field<bool> ctime;
    #pragma endregion Fields

    #pragma region Constructors
    VarDef(field<identifier> name, maybe<expr> type, maybe<expr> value, field<bool> mut, field<bool> ctime) :
        name{std::move(name)}, type{std::move(type)}, value{std::move(value)}, mut{std::move(mut)}, ctime{std::move(ctime)} {}
    #pragma endregion Constructors
    
    #pragma region Service constructors
    VarDef(const VarDef &) = delete;
    VarDef(VarDef &&) = default;
    VarDef &operator=(const VarDef &) = delete;
    VarDef &operator=(VarDef &&) = default;
    #pragma endregion Service constructors

    #pragma region Uniform fields access
    /**
     * Returns a tuple of references to all fields.
     * Note that the tuple may include sequences (std::vector) and optional fields (null unique_ptr's).
     */
    auto get_fields_tuple() {
        return std::tie(name, type, value, mut, ctime);
    }
    #pragma endregion Uniform fields access

    #pragma region Extras
    
    #pragma endregion Extras
};


class Impl : _ConcreteASTNode {
public:
    #pragma region Fields
    field<identifier> class_name;
    std::optional<identifier> trait_name;
    field<expr> body;
    field<bool> ctime;
    #pragma endregion Fields

    #pragma region Constructors
    Impl(field<identifier> class_name, std::optional<identifier> trait_name, field<expr> body, field<bool> ctime) :
        class_name{std::move(class_name)}, trait_name{std::move(trait_name)}, body{std::move(body)}, ctime{std::move(ctime)} {}
    #pragma endregion Constructors
    
    #pragma region Service constructors
    Impl(const Impl &) = delete;
    Impl(Impl &&) = default;
    Impl &operator=(const Impl &) = delete;
    Impl &operator=(Impl &&) = default;
    #pragma endregion Service constructors

    #pragma region Uniform fields access
    /**
     * Returns a tuple of references to all fields.
     * Note that the tuple may include sequences (std::vector) and optional fields (null unique_ptr's).
     */
    auto get_fields_tuple() {
        return std::tie(class_name, trait_name, body, ctime);
    }
    #pragma endregion Uniform fields access

    #pragma region Extras
    
    #pragma endregion Extras
};


class Assign : _ConcreteASTNode {
public:
    #pragma region Fields
    field<expr> target;
    field<expr> value;
    field<assign_op> op;
    #pragma endregion Fields

    #pragma region Constructors
    Assign(field<expr> target, field<expr> value, field<assign_op> op) :
        target{std::move(target)}, value{std::move(value)}, op{std::move(op)} {}
    #pragma endregion Constructors
    
    #pragma region Service constructors
    Assign(const Assign &) = delete;
    Assign(Assign &&) = default;
    Assign &operator=(const Assign &) = delete;
    Assign &operator=(Assign &&) = default;
    #pragma endregion Service constructors

    #pragma region Uniform fields access
    /**
     * Returns a tuple of references to all fields.
     * Note that the tuple may include sequences (std::vector) and optional fields (null unique_ptr's).
     */
    auto get_fields_tuple() {
        return std::tie(target, value, op);
    }
    #pragma endregion Uniform fields access

    #pragma region Extras
    
    #pragma endregion Extras
};


class Expr : _ConcreteASTNode {
public:
    #pragma region Fields
    field<expr> value;
    #pragma endregion Fields

    #pragma region Constructors
    Expr(field<expr> value) :
        value{std::move(value)} {}
    #pragma endregion Constructors
    
    #pragma region Service constructors
    Expr(const Expr &) = delete;
    Expr(Expr &&) = default;
    Expr &operator=(const Expr &) = delete;
    Expr &operator=(Expr &&) = default;
    #pragma endregion Service constructors

    #pragma region Uniform fields access
    /**
     * Returns a tuple of references to all fields.
     * Note that the tuple may include sequences (std::vector) and optional fields (null unique_ptr's).
     */
    auto get_fields_tuple() {
        return std::tie(value);
    }
    #pragma endregion Uniform fields access

    #pragma region Extras
    
    #pragma endregion Extras
};


class Pass : _ConcreteASTNode {
public:
    #pragma region Fields
    #pragma endregion Fields

    #pragma region Constructors
    Pass() {};
    #pragma endregion Constructors
    
    #pragma region Service constructors
    Pass(const Pass &) = default;
    Pass(Pass &&) = default;
    Pass &operator=(const Pass &) = default;
    Pass &operator=(Pass &&) = default;
    #pragma endregion Service constructors

    #pragma region Uniform fields access
    /**
     * Returns a tuple of references to all fields.
     * Note that the tuple may include sequences (std::vector) and optional fields (null unique_ptr's).
     */
    auto get_fields_tuple() {
        return std::tie();
    }
    #pragma endregion Uniform fields access

    #pragma region Extras
    
    #pragma endregion Extras
};


class expr : public _AST<Name, Constant, Attribute, Call, Subscript, Block, FuncDef, ClassDef, BinOp, UnOp, Compare, BoolOp, If, For, While, Return, Break, Continue, Tuple> {
public:
    #pragma region Constructors
    expr(auto &&value)
        : _AST(std::forward<decltype(value)>(value)) {}
    #pragma endregion Constructors
    
    #pragma region Service constructors
    expr(const expr &) = delete;
    expr(expr &&) = default;
    expr &operator=(const expr &) = delete;
    expr &operator=(expr &&) = default;
    #pragma endregion Service constructors

    #pragma region Destructor
    ~expr() = default;
    #pragma endregion Destructor

    #pragma region Attributes
    
    #pragma endregion Attributes

    #pragma region Extras
    
    #pragma endregion Extras
};


class Name : _ConcreteASTNode {
public:
    #pragma region Fields
    field<identifier> value;
    #pragma endregion Fields

    #pragma region Constructors
    Name(field<identifier> value) :
        value{std::move(value)} {}
    #pragma endregion Constructors
    
    #pragma region Service constructors
    Name(const Name &) = delete;
    Name(Name &&) = default;
    Name &operator=(const Name &) = delete;
    Name &operator=(Name &&) = default;
    #pragma endregion Service constructors

    #pragma region Uniform fields access
    /**
     * Returns a tuple of references to all fields.
     * Note that the tuple may include sequences (std::vector) and optional fields (null unique_ptr's).
     */
    auto get_fields_tuple() {
        return std::tie(value);
    }
    #pragma endregion Uniform fields access

    #pragma region Extras
    
    #pragma endregion Extras
};


class Constant : _ConcreteASTNode {
public:
    #pragma region Fields
    field<constant> value;
    #pragma endregion Fields

    #pragma region Constructors
    Constant(field<constant> value) :
        value{std::move(value)} {}
    #pragma endregion Constructors
    
    #pragma region Service constructors
    Constant(const Constant &) = delete;
    Constant(Constant &&) = default;
    Constant &operator=(const Constant &) = delete;
    Constant &operator=(Constant &&) = default;
    #pragma endregion Service constructors

    #pragma region Uniform fields access
    /**
     * Returns a tuple of references to all fields.
     * Note that the tuple may include sequences (std::vector) and optional fields (null unique_ptr's).
     */
    auto get_fields_tuple() {
        return std::tie(value);
    }
    #pragma endregion Uniform fields access

    #pragma region Extras
    
    #pragma endregion Extras
};


class Attribute : _ConcreteASTNode {
public:
    #pragma region Fields
    field<expr> value;
    field<identifier> attr;
    field<attr_op> type;
    #pragma endregion Fields

    #pragma region Constructors
    Attribute(field<expr> value, field<identifier> attr, field<attr_op> type) :
        value{std::move(value)}, attr{std::move(attr)}, type{std::move(type)} {}
    #pragma endregion Constructors
    
    #pragma region Service constructors
    Attribute(const Attribute &) = delete;
    Attribute(Attribute &&) = default;
    Attribute &operator=(const Attribute &) = delete;
    Attribute &operator=(Attribute &&) = default;
    #pragma endregion Service constructors

    #pragma region Uniform fields access
    /**
     * Returns a tuple of references to all fields.
     * Note that the tuple may include sequences (std::vector) and optional fields (null unique_ptr's).
     */
    auto get_fields_tuple() {
        return std::tie(value, attr, type);
    }
    #pragma endregion Uniform fields access

    #pragma region Extras
    
    #pragma endregion Extras
};


class Call : _ConcreteASTNode {
public:
    #pragma region Fields
    field<expr> func;
    field<call_args> args;
    #pragma endregion Fields

    #pragma region Constructors
    Call(field<expr> func, field<call_args> args) :
        func{std::move(func)}, args{std::move(args)} {}
    #pragma endregion Constructors
    
    #pragma region Service constructors
    Call(const Call &) = delete;
    Call(Call &&) = default;
    Call &operator=(const Call &) = delete;
    Call &operator=(Call &&) = default;
    #pragma endregion Service constructors

    #pragma region Uniform fields access
    /**
     * Returns a tuple of references to all fields.
     * Note that the tuple may include sequences (std::vector) and optional fields (null unique_ptr's).
     */
    auto get_fields_tuple() {
        return std::tie(func, args);
    }
    #pragma endregion Uniform fields access

    #pragma region Extras
    
    #pragma endregion Extras
};


class Subscript : _ConcreteASTNode {
public:
    #pragma region Fields
    field<expr> value;
    field<call_args> args;
    #pragma endregion Fields

    #pragma region Constructors
    Subscript(field<expr> value, field<call_args> args) :
        value{std::move(value)}, args{std::move(args)} {}
    #pragma endregion Constructors
    
    #pragma region Service constructors
    Subscript(const Subscript &) = delete;
    Subscript(Subscript &&) = default;
    Subscript &operator=(const Subscript &) = delete;
    Subscript &operator=(Subscript &&) = default;
    #pragma endregion Service constructors

    #pragma region Uniform fields access
    /**
     * Returns a tuple of references to all fields.
     * Note that the tuple may include sequences (std::vector) and optional fields (null unique_ptr's).
     */
    auto get_fields_tuple() {
        return std::tie(value, args);
    }
    #pragma endregion Uniform fields access

    #pragma region Extras
    
    #pragma endregion Extras
};


class Block : _ConcreteASTNode {
public:
    #pragma region Fields
    sequence<stmt> body;
    field<expr> value;
    field<bool> ctime;
    #pragma endregion Fields

    #pragma region Constructors
    Block(sequence<stmt> body, field<expr> value, field<bool> ctime) :
        body{std::move(body)}, value{std::move(value)}, ctime{std::move(ctime)} {}
    #pragma endregion Constructors
    
    #pragma region Service constructors
    Block(const Block &) = delete;
    Block(Block &&) = default;
    Block &operator=(const Block &) = delete;
    Block &operator=(Block &&) = default;
    #pragma endregion Service constructors

    #pragma region Uniform fields access
    /**
     * Returns a tuple of references to all fields.
     * Note that the tuple may include sequences (std::vector) and optional fields (null unique_ptr's).
     */
    auto get_fields_tuple() {
        return std::tie(body, value, ctime);
    }
    #pragma endregion Uniform fields access

    #pragma region Extras
    
    #pragma endregion Extras
};


class FuncDef : _ConcreteASTNode {
public:
    #pragma region Fields
    field<identifier> name;
    field<arg_defs> args;
    maybe<expr> return_type;
    field<expr> body;
    #pragma endregion Fields

    #pragma region Constructors
    FuncDef(field<identifier> name, field<arg_defs> args, maybe<expr> return_type, field<expr> body) :
        name{std::move(name)}, args{std::move(args)}, return_type{std::move(return_type)}, body{std::move(body)} {}
    #pragma endregion Constructors
    
    #pragma region Service constructors
    FuncDef(const FuncDef &) = delete;
    FuncDef(FuncDef &&) = default;
    FuncDef &operator=(const FuncDef &) = delete;
    FuncDef &operator=(FuncDef &&) = default;
    #pragma endregion Service constructors

    #pragma region Uniform fields access
    /**
     * Returns a tuple of references to all fields.
     * Note that the tuple may include sequences (std::vector) and optional fields (null unique_ptr's).
     */
    auto get_fields_tuple() {
        return std::tie(name, args, return_type, body);
    }
    #pragma endregion Uniform fields access

    #pragma region Extras
    // TODO: Subject to changes!
    constexpr bool is_ctime() const {
        if (!body->is<Block>())
            return false;

        return body->as<Block>().ctime;
    }

    #pragma endregion Extras
};


class ClassDef : _ConcreteASTNode {
public:
    #pragma region Fields
    field<identifier> name;
    field<expr> body;
    field<bool> ctime;
    #pragma endregion Fields

    #pragma region Constructors
    ClassDef(field<identifier> name, field<expr> body, field<bool> ctime) :
        name{std::move(name)}, body{std::move(body)}, ctime{std::move(ctime)} {}
    #pragma endregion Constructors
    
    #pragma region Service constructors
    ClassDef(const ClassDef &) = delete;
    ClassDef(ClassDef &&) = default;
    ClassDef &operator=(const ClassDef &) = delete;
    ClassDef &operator=(ClassDef &&) = default;
    #pragma endregion Service constructors

    #pragma region Uniform fields access
    /**
     * Returns a tuple of references to all fields.
     * Note that the tuple may include sequences (std::vector) and optional fields (null unique_ptr's).
     */
    auto get_fields_tuple() {
        return std::tie(name, body, ctime);
    }
    #pragma endregion Uniform fields access

    #pragma region Extras
    
    #pragma endregion Extras
};


class BinOp : _ConcreteASTNode {
public:
    #pragma region Fields
    field<expr> left;
    field<binary_op> op;
    field<expr> right;
    #pragma endregion Fields

    #pragma region Constructors
    BinOp(field<expr> left, field<binary_op> op, field<expr> right) :
        left{std::move(left)}, op{std::move(op)}, right{std::move(right)} {}
    #pragma endregion Constructors
    
    #pragma region Service constructors
    BinOp(const BinOp &) = delete;
    BinOp(BinOp &&) = default;
    BinOp &operator=(const BinOp &) = delete;
    BinOp &operator=(BinOp &&) = default;
    #pragma endregion Service constructors

    #pragma region Uniform fields access
    /**
     * Returns a tuple of references to all fields.
     * Note that the tuple may include sequences (std::vector) and optional fields (null unique_ptr's).
     */
    auto get_fields_tuple() {
        return std::tie(left, op, right);
    }
    #pragma endregion Uniform fields access

    #pragma region Extras
    
    #pragma endregion Extras
};


class UnOp : _ConcreteASTNode {
public:
    #pragma region Fields
    field<unary_op> op;
    field<expr> operand;
    #pragma endregion Fields

    #pragma region Constructors
    UnOp(field<unary_op> op, field<expr> operand) :
        op{std::move(op)}, operand{std::move(operand)} {}
    #pragma endregion Constructors
    
    #pragma region Service constructors
    UnOp(const UnOp &) = delete;
    UnOp(UnOp &&) = default;
    UnOp &operator=(const UnOp &) = delete;
    UnOp &operator=(UnOp &&) = default;
    #pragma endregion Service constructors

    #pragma region Uniform fields access
    /**
     * Returns a tuple of references to all fields.
     * Note that the tuple may include sequences (std::vector) and optional fields (null unique_ptr's).
     */
    auto get_fields_tuple() {
        return std::tie(op, operand);
    }
    #pragma endregion Uniform fields access

    #pragma region Extras
    
    #pragma endregion Extras
};


class Compare : _ConcreteASTNode {
public:
    #pragma region Fields
    field<expr> left;
    sequence<cmp_op> op;
    sequence<expr> operands;
    #pragma endregion Fields

    #pragma region Constructors
    Compare(field<expr> left, sequence<cmp_op> op, sequence<expr> operands) :
        left{std::move(left)}, op{std::move(op)}, operands{std::move(operands)} {}
    #pragma endregion Constructors
    
    #pragma region Service constructors
    Compare(const Compare &) = delete;
    Compare(Compare &&) = default;
    Compare &operator=(const Compare &) = delete;
    Compare &operator=(Compare &&) = default;
    #pragma endregion Service constructors

    #pragma region Uniform fields access
    /**
     * Returns a tuple of references to all fields.
     * Note that the tuple may include sequences (std::vector) and optional fields (null unique_ptr's).
     */
    auto get_fields_tuple() {
        return std::tie(left, op, operands);
    }
    #pragma endregion Uniform fields access

    #pragma region Extras
    
    #pragma endregion Extras
};


class BoolOp : _ConcreteASTNode {
public:
    #pragma region Fields
    field<bool_op> op;
    sequence<expr> values;
    #pragma endregion Fields

    #pragma region Constructors
    BoolOp(field<bool_op> op, sequence<expr> values) :
        op{std::move(op)}, values{std::move(values)} {}
    #pragma endregion Constructors
    
    #pragma region Service constructors
    BoolOp(const BoolOp &) = delete;
    BoolOp(BoolOp &&) = default;
    BoolOp &operator=(const BoolOp &) = delete;
    BoolOp &operator=(BoolOp &&) = default;
    #pragma endregion Service constructors

    #pragma region Uniform fields access
    /**
     * Returns a tuple of references to all fields.
     * Note that the tuple may include sequences (std::vector) and optional fields (null unique_ptr's).
     */
    auto get_fields_tuple() {
        return std::tie(op, values);
    }
    #pragma endregion Uniform fields access

    #pragma region Extras
    
    #pragma endregion Extras
};


class If : _ConcreteASTNode {
public:
    #pragma region Fields
    field<expr> cond;
    field<expr> body;
    field<expr> orelse;
    #pragma endregion Fields

    #pragma region Constructors
    If(field<expr> cond, field<expr> body, field<expr> orelse) :
        cond{std::move(cond)}, body{std::move(body)}, orelse{std::move(orelse)} {}
    #pragma endregion Constructors
    
    #pragma region Service constructors
    If(const If &) = delete;
    If(If &&) = default;
    If &operator=(const If &) = delete;
    If &operator=(If &&) = default;
    #pragma endregion Service constructors

    #pragma region Uniform fields access
    /**
     * Returns a tuple of references to all fields.
     * Note that the tuple may include sequences (std::vector) and optional fields (null unique_ptr's).
     */
    auto get_fields_tuple() {
        return std::tie(cond, body, orelse);
    }
    #pragma endregion Uniform fields access

    #pragma region Extras
    
    #pragma endregion Extras
};


class For : _ConcreteASTNode {
public:
    #pragma region Fields
    field<identifier> var;
    field<expr> iter;
    field<expr> body;
    field<expr> orelse;
    #pragma endregion Fields

    #pragma region Constructors
    For(field<identifier> var, field<expr> iter, field<expr> body, field<expr> orelse) :
        var{std::move(var)}, iter{std::move(iter)}, body{std::move(body)}, orelse{std::move(orelse)} {}
    #pragma endregion Constructors
    
    #pragma region Service constructors
    For(const For &) = delete;
    For(For &&) = default;
    For &operator=(const For &) = delete;
    For &operator=(For &&) = default;
    #pragma endregion Service constructors

    #pragma region Uniform fields access
    /**
     * Returns a tuple of references to all fields.
     * Note that the tuple may include sequences (std::vector) and optional fields (null unique_ptr's).
     */
    auto get_fields_tuple() {
        return std::tie(var, iter, body, orelse);
    }
    #pragma endregion Uniform fields access

    #pragma region Extras
    
    #pragma endregion Extras
};


class While : _ConcreteASTNode {
public:
    #pragma region Fields
    field<expr> cond;
    field<expr> body;
    maybe<expr> orelse;
    #pragma endregion Fields

    #pragma region Constructors
    While(field<expr> cond, field<expr> body, maybe<expr> orelse) :
        cond{std::move(cond)}, body{std::move(body)}, orelse{std::move(orelse)} {}
    #pragma endregion Constructors
    
    #pragma region Service constructors
    While(const While &) = delete;
    While(While &&) = default;
    While &operator=(const While &) = delete;
    While &operator=(While &&) = default;
    #pragma endregion Service constructors

    #pragma region Uniform fields access
    /**
     * Returns a tuple of references to all fields.
     * Note that the tuple may include sequences (std::vector) and optional fields (null unique_ptr's).
     */
    auto get_fields_tuple() {
        return std::tie(cond, body, orelse);
    }
    #pragma endregion Uniform fields access

    #pragma region Extras
    
    #pragma endregion Extras
};


class Return : _ConcreteASTNode {
public:
    #pragma region Fields
    field<expr> value;
    #pragma endregion Fields

    #pragma region Constructors
    Return(field<expr> value) :
        value{std::move(value)} {}
    #pragma endregion Constructors
    
    #pragma region Service constructors
    Return(const Return &) = delete;
    Return(Return &&) = default;
    Return &operator=(const Return &) = delete;
    Return &operator=(Return &&) = default;
    #pragma endregion Service constructors

    #pragma region Uniform fields access
    /**
     * Returns a tuple of references to all fields.
     * Note that the tuple may include sequences (std::vector) and optional fields (null unique_ptr's).
     */
    auto get_fields_tuple() {
        return std::tie(value);
    }
    #pragma endregion Uniform fields access

    #pragma region Extras
    
    #pragma endregion Extras
};


class Break : _ConcreteASTNode {
public:
    #pragma region Fields
    field<expr> value;
    #pragma endregion Fields

    #pragma region Constructors
    Break(field<expr> value) :
        value{std::move(value)} {}
    #pragma endregion Constructors
    
    #pragma region Service constructors
    Break(const Break &) = delete;
    Break(Break &&) = default;
    Break &operator=(const Break &) = delete;
    Break &operator=(Break &&) = default;
    #pragma endregion Service constructors

    #pragma region Uniform fields access
    /**
     * Returns a tuple of references to all fields.
     * Note that the tuple may include sequences (std::vector) and optional fields (null unique_ptr's).
     */
    auto get_fields_tuple() {
        return std::tie(value);
    }
    #pragma endregion Uniform fields access

    #pragma region Extras
    
    #pragma endregion Extras
};


class Continue : _ConcreteASTNode {
public:
    #pragma region Fields
    #pragma endregion Fields

    #pragma region Constructors
    Continue() {};
    #pragma endregion Constructors
    
    #pragma region Service constructors
    Continue(const Continue &) = default;
    Continue(Continue &&) = default;
    Continue &operator=(const Continue &) = default;
    Continue &operator=(Continue &&) = default;
    #pragma endregion Service constructors

    #pragma region Uniform fields access
    /**
     * Returns a tuple of references to all fields.
     * Note that the tuple may include sequences (std::vector) and optional fields (null unique_ptr's).
     */
    auto get_fields_tuple() {
        return std::tie();
    }
    #pragma endregion Uniform fields access

    #pragma region Extras
    
    #pragma endregion Extras
};


class Tuple : _ConcreteASTNode {
public:
    #pragma region Fields
    sequence<expr> values;
    #pragma endregion Fields

    #pragma region Constructors
    Tuple(sequence<expr> values) :
        values{std::move(values)} {}
    #pragma endregion Constructors
    
    #pragma region Service constructors
    Tuple(const Tuple &) = delete;
    Tuple(Tuple &&) = default;
    Tuple &operator=(const Tuple &) = delete;
    Tuple &operator=(Tuple &&) = default;
    #pragma endregion Service constructors

    #pragma region Uniform fields access
    /**
     * Returns a tuple of references to all fields.
     * Note that the tuple may include sequences (std::vector) and optional fields (null unique_ptr's).
     */
    auto get_fields_tuple() {
        return std::tie(values);
    }
    #pragma endregion Uniform fields access

    #pragma region Extras
    
    #pragma endregion Extras
};


class assign_op : public _AST<AsgnNone, AsgnAdd, AsgnSub, AsgnMul, AsgnDiv, AsgnMod, AsgnLShift, AsgnRShift, AsgnBitOr, AsgnBitXor, AsgnBitAnd> {
public:
    #pragma region Constructors
    assign_op(auto &&value)
        : _AST(std::forward<decltype(value)>(value)) {}
    #pragma endregion Constructors
    
    #pragma region Service constructors
    assign_op(const assign_op &) = default;
    assign_op(assign_op &&) = default;
    assign_op &operator=(const assign_op &) = default;
    assign_op &operator=(assign_op &&) = default;
    #pragma endregion Service constructors

    #pragma region Destructor
    ~assign_op() = default;
    #pragma endregion Destructor

    #pragma region Attributes
    
    #pragma endregion Attributes

    #pragma region Extras
    
    #pragma endregion Extras
};


class AsgnNone : _ConcreteASTNode {
public:
    #pragma region Fields
    #pragma endregion Fields

    #pragma region Constructors
    AsgnNone() {};
    #pragma endregion Constructors
    
    #pragma region Service constructors
    AsgnNone(const AsgnNone &) = default;
    AsgnNone(AsgnNone &&) = default;
    AsgnNone &operator=(const AsgnNone &) = default;
    AsgnNone &operator=(AsgnNone &&) = default;
    #pragma endregion Service constructors

    #pragma region Uniform fields access
    /**
     * Returns a tuple of references to all fields.
     * Note that the tuple may include sequences (std::vector) and optional fields (null unique_ptr's).
     */
    auto get_fields_tuple() {
        return std::tie();
    }
    #pragma endregion Uniform fields access

    #pragma region Extras
    
    #pragma endregion Extras
};


class AsgnAdd : _ConcreteASTNode {
public:
    #pragma region Fields
    #pragma endregion Fields

    #pragma region Constructors
    AsgnAdd() {};
    #pragma endregion Constructors
    
    #pragma region Service constructors
    AsgnAdd(const AsgnAdd &) = default;
    AsgnAdd(AsgnAdd &&) = default;
    AsgnAdd &operator=(const AsgnAdd &) = default;
    AsgnAdd &operator=(AsgnAdd &&) = default;
    #pragma endregion Service constructors

    #pragma region Uniform fields access
    /**
     * Returns a tuple of references to all fields.
     * Note that the tuple may include sequences (std::vector) and optional fields (null unique_ptr's).
     */
    auto get_fields_tuple() {
        return std::tie();
    }
    #pragma endregion Uniform fields access

    #pragma region Extras
    
    #pragma endregion Extras
};


class AsgnSub : _ConcreteASTNode {
public:
    #pragma region Fields
    #pragma endregion Fields

    #pragma region Constructors
    AsgnSub() {};
    #pragma endregion Constructors
    
    #pragma region Service constructors
    AsgnSub(const AsgnSub &) = default;
    AsgnSub(AsgnSub &&) = default;
    AsgnSub &operator=(const AsgnSub &) = default;
    AsgnSub &operator=(AsgnSub &&) = default;
    #pragma endregion Service constructors

    #pragma region Uniform fields access
    /**
     * Returns a tuple of references to all fields.
     * Note that the tuple may include sequences (std::vector) and optional fields (null unique_ptr's).
     */
    auto get_fields_tuple() {
        return std::tie();
    }
    #pragma endregion Uniform fields access

    #pragma region Extras
    
    #pragma endregion Extras
};


class AsgnMul : _ConcreteASTNode {
public:
    #pragma region Fields
    #pragma endregion Fields

    #pragma region Constructors
    AsgnMul() {};
    #pragma endregion Constructors
    
    #pragma region Service constructors
    AsgnMul(const AsgnMul &) = default;
    AsgnMul(AsgnMul &&) = default;
    AsgnMul &operator=(const AsgnMul &) = default;
    AsgnMul &operator=(AsgnMul &&) = default;
    #pragma endregion Service constructors

    #pragma region Uniform fields access
    /**
     * Returns a tuple of references to all fields.
     * Note that the tuple may include sequences (std::vector) and optional fields (null unique_ptr's).
     */
    auto get_fields_tuple() {
        return std::tie();
    }
    #pragma endregion Uniform fields access

    #pragma region Extras
    
    #pragma endregion Extras
};


class AsgnDiv : _ConcreteASTNode {
public:
    #pragma region Fields
    #pragma endregion Fields

    #pragma region Constructors
    AsgnDiv() {};
    #pragma endregion Constructors
    
    #pragma region Service constructors
    AsgnDiv(const AsgnDiv &) = default;
    AsgnDiv(AsgnDiv &&) = default;
    AsgnDiv &operator=(const AsgnDiv &) = default;
    AsgnDiv &operator=(AsgnDiv &&) = default;
    #pragma endregion Service constructors

    #pragma region Uniform fields access
    /**
     * Returns a tuple of references to all fields.
     * Note that the tuple may include sequences (std::vector) and optional fields (null unique_ptr's).
     */
    auto get_fields_tuple() {
        return std::tie();
    }
    #pragma endregion Uniform fields access

    #pragma region Extras
    
    #pragma endregion Extras
};


class AsgnMod : _ConcreteASTNode {
public:
    #pragma region Fields
    #pragma endregion Fields

    #pragma region Constructors
    AsgnMod() {};
    #pragma endregion Constructors
    
    #pragma region Service constructors
    AsgnMod(const AsgnMod &) = default;
    AsgnMod(AsgnMod &&) = default;
    AsgnMod &operator=(const AsgnMod &) = default;
    AsgnMod &operator=(AsgnMod &&) = default;
    #pragma endregion Service constructors

    #pragma region Uniform fields access
    /**
     * Returns a tuple of references to all fields.
     * Note that the tuple may include sequences (std::vector) and optional fields (null unique_ptr's).
     */
    auto get_fields_tuple() {
        return std::tie();
    }
    #pragma endregion Uniform fields access

    #pragma region Extras
    
    #pragma endregion Extras
};


class AsgnLShift : _ConcreteASTNode {
public:
    #pragma region Fields
    #pragma endregion Fields

    #pragma region Constructors
    AsgnLShift() {};
    #pragma endregion Constructors
    
    #pragma region Service constructors
    AsgnLShift(const AsgnLShift &) = default;
    AsgnLShift(AsgnLShift &&) = default;
    AsgnLShift &operator=(const AsgnLShift &) = default;
    AsgnLShift &operator=(AsgnLShift &&) = default;
    #pragma endregion Service constructors

    #pragma region Uniform fields access
    /**
     * Returns a tuple of references to all fields.
     * Note that the tuple may include sequences (std::vector) and optional fields (null unique_ptr's).
     */
    auto get_fields_tuple() {
        return std::tie();
    }
    #pragma endregion Uniform fields access

    #pragma region Extras
    
    #pragma endregion Extras
};


class AsgnRShift : _ConcreteASTNode {
public:
    #pragma region Fields
    #pragma endregion Fields

    #pragma region Constructors
    AsgnRShift() {};
    #pragma endregion Constructors
    
    #pragma region Service constructors
    AsgnRShift(const AsgnRShift &) = default;
    AsgnRShift(AsgnRShift &&) = default;
    AsgnRShift &operator=(const AsgnRShift &) = default;
    AsgnRShift &operator=(AsgnRShift &&) = default;
    #pragma endregion Service constructors

    #pragma region Uniform fields access
    /**
     * Returns a tuple of references to all fields.
     * Note that the tuple may include sequences (std::vector) and optional fields (null unique_ptr's).
     */
    auto get_fields_tuple() {
        return std::tie();
    }
    #pragma endregion Uniform fields access

    #pragma region Extras
    
    #pragma endregion Extras
};


class AsgnBitOr : _ConcreteASTNode {
public:
    #pragma region Fields
    #pragma endregion Fields

    #pragma region Constructors
    AsgnBitOr() {};
    #pragma endregion Constructors
    
    #pragma region Service constructors
    AsgnBitOr(const AsgnBitOr &) = default;
    AsgnBitOr(AsgnBitOr &&) = default;
    AsgnBitOr &operator=(const AsgnBitOr &) = default;
    AsgnBitOr &operator=(AsgnBitOr &&) = default;
    #pragma endregion Service constructors

    #pragma region Uniform fields access
    /**
     * Returns a tuple of references to all fields.
     * Note that the tuple may include sequences (std::vector) and optional fields (null unique_ptr's).
     */
    auto get_fields_tuple() {
        return std::tie();
    }
    #pragma endregion Uniform fields access

    #pragma region Extras
    
    #pragma endregion Extras
};


class AsgnBitXor : _ConcreteASTNode {
public:
    #pragma region Fields
    #pragma endregion Fields

    #pragma region Constructors
    AsgnBitXor() {};
    #pragma endregion Constructors
    
    #pragma region Service constructors
    AsgnBitXor(const AsgnBitXor &) = default;
    AsgnBitXor(AsgnBitXor &&) = default;
    AsgnBitXor &operator=(const AsgnBitXor &) = default;
    AsgnBitXor &operator=(AsgnBitXor &&) = default;
    #pragma endregion Service constructors

    #pragma region Uniform fields access
    /**
     * Returns a tuple of references to all fields.
     * Note that the tuple may include sequences (std::vector) and optional fields (null unique_ptr's).
     */
    auto get_fields_tuple() {
        return std::tie();
    }
    #pragma endregion Uniform fields access

    #pragma region Extras
    
    #pragma endregion Extras
};


class AsgnBitAnd : _ConcreteASTNode {
public:
    #pragma region Fields
    #pragma endregion Fields

    #pragma region Constructors
    AsgnBitAnd() {};
    #pragma endregion Constructors
    
    #pragma region Service constructors
    AsgnBitAnd(const AsgnBitAnd &) = default;
    AsgnBitAnd(AsgnBitAnd &&) = default;
    AsgnBitAnd &operator=(const AsgnBitAnd &) = default;
    AsgnBitAnd &operator=(AsgnBitAnd &&) = default;
    #pragma endregion Service constructors

    #pragma region Uniform fields access
    /**
     * Returns a tuple of references to all fields.
     * Note that the tuple may include sequences (std::vector) and optional fields (null unique_ptr's).
     */
    auto get_fields_tuple() {
        return std::tie();
    }
    #pragma endregion Uniform fields access

    #pragma region Extras
    
    #pragma endregion Extras
};


class bool_op : public _AST<And, Or> {
public:
    #pragma region Constructors
    bool_op(auto &&value)
        : _AST(std::forward<decltype(value)>(value)) {}
    #pragma endregion Constructors
    
    #pragma region Service constructors
    bool_op(const bool_op &) = default;
    bool_op(bool_op &&) = default;
    bool_op &operator=(const bool_op &) = default;
    bool_op &operator=(bool_op &&) = default;
    #pragma endregion Service constructors

    #pragma region Destructor
    ~bool_op() = default;
    #pragma endregion Destructor

    #pragma region Attributes
    
    #pragma endregion Attributes

    #pragma region Extras
    
    #pragma endregion Extras
};


class And : _ConcreteASTNode {
public:
    #pragma region Fields
    #pragma endregion Fields

    #pragma region Constructors
    And() {};
    #pragma endregion Constructors
    
    #pragma region Service constructors
    And(const And &) = default;
    And(And &&) = default;
    And &operator=(const And &) = default;
    And &operator=(And &&) = default;
    #pragma endregion Service constructors

    #pragma region Uniform fields access
    /**
     * Returns a tuple of references to all fields.
     * Note that the tuple may include sequences (std::vector) and optional fields (null unique_ptr's).
     */
    auto get_fields_tuple() {
        return std::tie();
    }
    #pragma endregion Uniform fields access

    #pragma region Extras
    
    #pragma endregion Extras
};


class Or : _ConcreteASTNode {
public:
    #pragma region Fields
    #pragma endregion Fields

    #pragma region Constructors
    Or() {};
    #pragma endregion Constructors
    
    #pragma region Service constructors
    Or(const Or &) = default;
    Or(Or &&) = default;
    Or &operator=(const Or &) = default;
    Or &operator=(Or &&) = default;
    #pragma endregion Service constructors

    #pragma region Uniform fields access
    /**
     * Returns a tuple of references to all fields.
     * Note that the tuple may include sequences (std::vector) and optional fields (null unique_ptr's).
     */
    auto get_fields_tuple() {
        return std::tie();
    }
    #pragma endregion Uniform fields access

    #pragma region Extras
    
    #pragma endregion Extras
};


class binary_op : public _AST<Add, Sub, Mul, Div, Mod, Pow, LShift, RShift, BitOr, BitXor, BitAnd, BidirCmp> {
public:
    #pragma region Constructors
    binary_op(auto &&value)
        : _AST(std::forward<decltype(value)>(value)) {}
    #pragma endregion Constructors
    
    #pragma region Service constructors
    binary_op(const binary_op &) = default;
    binary_op(binary_op &&) = default;
    binary_op &operator=(const binary_op &) = default;
    binary_op &operator=(binary_op &&) = default;
    #pragma endregion Service constructors

    #pragma region Destructor
    ~binary_op() = default;
    #pragma endregion Destructor

    #pragma region Attributes
    
    #pragma endregion Attributes

    #pragma region Extras
    
    #pragma endregion Extras
};


class Add : _ConcreteASTNode {
public:
    #pragma region Fields
    #pragma endregion Fields

    #pragma region Constructors
    Add() {};
    #pragma endregion Constructors
    
    #pragma region Service constructors
    Add(const Add &) = default;
    Add(Add &&) = default;
    Add &operator=(const Add &) = default;
    Add &operator=(Add &&) = default;
    #pragma endregion Service constructors

    #pragma region Uniform fields access
    /**
     * Returns a tuple of references to all fields.
     * Note that the tuple may include sequences (std::vector) and optional fields (null unique_ptr's).
     */
    auto get_fields_tuple() {
        return std::tie();
    }
    #pragma endregion Uniform fields access

    #pragma region Extras
    
    #pragma endregion Extras
};


class Sub : _ConcreteASTNode {
public:
    #pragma region Fields
    #pragma endregion Fields

    #pragma region Constructors
    Sub() {};
    #pragma endregion Constructors
    
    #pragma region Service constructors
    Sub(const Sub &) = default;
    Sub(Sub &&) = default;
    Sub &operator=(const Sub &) = default;
    Sub &operator=(Sub &&) = default;
    #pragma endregion Service constructors

    #pragma region Uniform fields access
    /**
     * Returns a tuple of references to all fields.
     * Note that the tuple may include sequences (std::vector) and optional fields (null unique_ptr's).
     */
    auto get_fields_tuple() {
        return std::tie();
    }
    #pragma endregion Uniform fields access

    #pragma region Extras
    
    #pragma endregion Extras
};


class Mul : _ConcreteASTNode {
public:
    #pragma region Fields
    #pragma endregion Fields

    #pragma region Constructors
    Mul() {};
    #pragma endregion Constructors
    
    #pragma region Service constructors
    Mul(const Mul &) = default;
    Mul(Mul &&) = default;
    Mul &operator=(const Mul &) = default;
    Mul &operator=(Mul &&) = default;
    #pragma endregion Service constructors

    #pragma region Uniform fields access
    /**
     * Returns a tuple of references to all fields.
     * Note that the tuple may include sequences (std::vector) and optional fields (null unique_ptr's).
     */
    auto get_fields_tuple() {
        return std::tie();
    }
    #pragma endregion Uniform fields access

    #pragma region Extras
    
    #pragma endregion Extras
};


class Div : _ConcreteASTNode {
public:
    #pragma region Fields
    #pragma endregion Fields

    #pragma region Constructors
    Div() {};
    #pragma endregion Constructors
    
    #pragma region Service constructors
    Div(const Div &) = default;
    Div(Div &&) = default;
    Div &operator=(const Div &) = default;
    Div &operator=(Div &&) = default;
    #pragma endregion Service constructors

    #pragma region Uniform fields access
    /**
     * Returns a tuple of references to all fields.
     * Note that the tuple may include sequences (std::vector) and optional fields (null unique_ptr's).
     */
    auto get_fields_tuple() {
        return std::tie();
    }
    #pragma endregion Uniform fields access

    #pragma region Extras
    
    #pragma endregion Extras
};


class Mod : _ConcreteASTNode {
public:
    #pragma region Fields
    #pragma endregion Fields

    #pragma region Constructors
    Mod() {};
    #pragma endregion Constructors
    
    #pragma region Service constructors
    Mod(const Mod &) = default;
    Mod(Mod &&) = default;
    Mod &operator=(const Mod &) = default;
    Mod &operator=(Mod &&) = default;
    #pragma endregion Service constructors

    #pragma region Uniform fields access
    /**
     * Returns a tuple of references to all fields.
     * Note that the tuple may include sequences (std::vector) and optional fields (null unique_ptr's).
     */
    auto get_fields_tuple() {
        return std::tie();
    }
    #pragma endregion Uniform fields access

    #pragma region Extras
    
    #pragma endregion Extras
};


class Pow : _ConcreteASTNode {
public:
    #pragma region Fields
    #pragma endregion Fields

    #pragma region Constructors
    Pow() {};
    #pragma endregion Constructors
    
    #pragma region Service constructors
    Pow(const Pow &) = default;
    Pow(Pow &&) = default;
    Pow &operator=(const Pow &) = default;
    Pow &operator=(Pow &&) = default;
    #pragma endregion Service constructors

    #pragma region Uniform fields access
    /**
     * Returns a tuple of references to all fields.
     * Note that the tuple may include sequences (std::vector) and optional fields (null unique_ptr's).
     */
    auto get_fields_tuple() {
        return std::tie();
    }
    #pragma endregion Uniform fields access

    #pragma region Extras
    
    #pragma endregion Extras
};


class LShift : _ConcreteASTNode {
public:
    #pragma region Fields
    #pragma endregion Fields

    #pragma region Constructors
    LShift() {};
    #pragma endregion Constructors
    
    #pragma region Service constructors
    LShift(const LShift &) = default;
    LShift(LShift &&) = default;
    LShift &operator=(const LShift &) = default;
    LShift &operator=(LShift &&) = default;
    #pragma endregion Service constructors

    #pragma region Uniform fields access
    /**
     * Returns a tuple of references to all fields.
     * Note that the tuple may include sequences (std::vector) and optional fields (null unique_ptr's).
     */
    auto get_fields_tuple() {
        return std::tie();
    }
    #pragma endregion Uniform fields access

    #pragma region Extras
    
    #pragma endregion Extras
};


class RShift : _ConcreteASTNode {
public:
    #pragma region Fields
    #pragma endregion Fields

    #pragma region Constructors
    RShift() {};
    #pragma endregion Constructors
    
    #pragma region Service constructors
    RShift(const RShift &) = default;
    RShift(RShift &&) = default;
    RShift &operator=(const RShift &) = default;
    RShift &operator=(RShift &&) = default;
    #pragma endregion Service constructors

    #pragma region Uniform fields access
    /**
     * Returns a tuple of references to all fields.
     * Note that the tuple may include sequences (std::vector) and optional fields (null unique_ptr's).
     */
    auto get_fields_tuple() {
        return std::tie();
    }
    #pragma endregion Uniform fields access

    #pragma region Extras
    
    #pragma endregion Extras
};


class BitOr : _ConcreteASTNode {
public:
    #pragma region Fields
    #pragma endregion Fields

    #pragma region Constructors
    BitOr() {};
    #pragma endregion Constructors
    
    #pragma region Service constructors
    BitOr(const BitOr &) = default;
    BitOr(BitOr &&) = default;
    BitOr &operator=(const BitOr &) = default;
    BitOr &operator=(BitOr &&) = default;
    #pragma endregion Service constructors

    #pragma region Uniform fields access
    /**
     * Returns a tuple of references to all fields.
     * Note that the tuple may include sequences (std::vector) and optional fields (null unique_ptr's).
     */
    auto get_fields_tuple() {
        return std::tie();
    }
    #pragma endregion Uniform fields access

    #pragma region Extras
    
    #pragma endregion Extras
};


class BitXor : _ConcreteASTNode {
public:
    #pragma region Fields
    #pragma endregion Fields

    #pragma region Constructors
    BitXor() {};
    #pragma endregion Constructors
    
    #pragma region Service constructors
    BitXor(const BitXor &) = default;
    BitXor(BitXor &&) = default;
    BitXor &operator=(const BitXor &) = default;
    BitXor &operator=(BitXor &&) = default;
    #pragma endregion Service constructors

    #pragma region Uniform fields access
    /**
     * Returns a tuple of references to all fields.
     * Note that the tuple may include sequences (std::vector) and optional fields (null unique_ptr's).
     */
    auto get_fields_tuple() {
        return std::tie();
    }
    #pragma endregion Uniform fields access

    #pragma region Extras
    
    #pragma endregion Extras
};


class BitAnd : _ConcreteASTNode {
public:
    #pragma region Fields
    #pragma endregion Fields

    #pragma region Constructors
    BitAnd() {};
    #pragma endregion Constructors
    
    #pragma region Service constructors
    BitAnd(const BitAnd &) = default;
    BitAnd(BitAnd &&) = default;
    BitAnd &operator=(const BitAnd &) = default;
    BitAnd &operator=(BitAnd &&) = default;
    #pragma endregion Service constructors

    #pragma region Uniform fields access
    /**
     * Returns a tuple of references to all fields.
     * Note that the tuple may include sequences (std::vector) and optional fields (null unique_ptr's).
     */
    auto get_fields_tuple() {
        return std::tie();
    }
    #pragma endregion Uniform fields access

    #pragma region Extras
    
    #pragma endregion Extras
};


class BidirCmp : _ConcreteASTNode {
public:
    #pragma region Fields
    #pragma endregion Fields

    #pragma region Constructors
    BidirCmp() {};
    #pragma endregion Constructors
    
    #pragma region Service constructors
    BidirCmp(const BidirCmp &) = default;
    BidirCmp(BidirCmp &&) = default;
    BidirCmp &operator=(const BidirCmp &) = default;
    BidirCmp &operator=(BidirCmp &&) = default;
    #pragma endregion Service constructors

    #pragma region Uniform fields access
    /**
     * Returns a tuple of references to all fields.
     * Note that the tuple may include sequences (std::vector) and optional fields (null unique_ptr's).
     */
    auto get_fields_tuple() {
        return std::tie();
    }
    #pragma endregion Uniform fields access

    #pragma region Extras
    
    #pragma endregion Extras
};


class unary_op : public _AST<BitInv, Not, UAdd, USub> {
public:
    #pragma region Constructors
    unary_op(auto &&value)
        : _AST(std::forward<decltype(value)>(value)) {}
    #pragma endregion Constructors
    
    #pragma region Service constructors
    unary_op(const unary_op &) = default;
    unary_op(unary_op &&) = default;
    unary_op &operator=(const unary_op &) = default;
    unary_op &operator=(unary_op &&) = default;
    #pragma endregion Service constructors

    #pragma region Destructor
    ~unary_op() = default;
    #pragma endregion Destructor

    #pragma region Attributes
    
    #pragma endregion Attributes

    #pragma region Extras
    
    #pragma endregion Extras
};


class BitInv : _ConcreteASTNode {
public:
    #pragma region Fields
    #pragma endregion Fields

    #pragma region Constructors
    BitInv() {};
    #pragma endregion Constructors
    
    #pragma region Service constructors
    BitInv(const BitInv &) = default;
    BitInv(BitInv &&) = default;
    BitInv &operator=(const BitInv &) = default;
    BitInv &operator=(BitInv &&) = default;
    #pragma endregion Service constructors

    #pragma region Uniform fields access
    /**
     * Returns a tuple of references to all fields.
     * Note that the tuple may include sequences (std::vector) and optional fields (null unique_ptr's).
     */
    auto get_fields_tuple() {
        return std::tie();
    }
    #pragma endregion Uniform fields access

    #pragma region Extras
    
    #pragma endregion Extras
};


class Not : _ConcreteASTNode {
public:
    #pragma region Fields
    #pragma endregion Fields

    #pragma region Constructors
    Not() {};
    #pragma endregion Constructors
    
    #pragma region Service constructors
    Not(const Not &) = default;
    Not(Not &&) = default;
    Not &operator=(const Not &) = default;
    Not &operator=(Not &&) = default;
    #pragma endregion Service constructors

    #pragma region Uniform fields access
    /**
     * Returns a tuple of references to all fields.
     * Note that the tuple may include sequences (std::vector) and optional fields (null unique_ptr's).
     */
    auto get_fields_tuple() {
        return std::tie();
    }
    #pragma endregion Uniform fields access

    #pragma region Extras
    
    #pragma endregion Extras
};


class UAdd : _ConcreteASTNode {
public:
    #pragma region Fields
    #pragma endregion Fields

    #pragma region Constructors
    UAdd() {};
    #pragma endregion Constructors
    
    #pragma region Service constructors
    UAdd(const UAdd &) = default;
    UAdd(UAdd &&) = default;
    UAdd &operator=(const UAdd &) = default;
    UAdd &operator=(UAdd &&) = default;
    #pragma endregion Service constructors

    #pragma region Uniform fields access
    /**
     * Returns a tuple of references to all fields.
     * Note that the tuple may include sequences (std::vector) and optional fields (null unique_ptr's).
     */
    auto get_fields_tuple() {
        return std::tie();
    }
    #pragma endregion Uniform fields access

    #pragma region Extras
    
    #pragma endregion Extras
};


class USub : _ConcreteASTNode {
public:
    #pragma region Fields
    #pragma endregion Fields

    #pragma region Constructors
    USub() {};
    #pragma endregion Constructors
    
    #pragma region Service constructors
    USub(const USub &) = default;
    USub(USub &&) = default;
    USub &operator=(const USub &) = default;
    USub &operator=(USub &&) = default;
    #pragma endregion Service constructors

    #pragma region Uniform fields access
    /**
     * Returns a tuple of references to all fields.
     * Note that the tuple may include sequences (std::vector) and optional fields (null unique_ptr's).
     */
    auto get_fields_tuple() {
        return std::tie();
    }
    #pragma endregion Uniform fields access

    #pragma region Extras
    
    #pragma endregion Extras
};


class cmp_op : public _AST<Eq, NotEq, Lt, LtE, Gt, GtE, In, NotIn> {
public:
    #pragma region Constructors
    cmp_op(auto &&value)
        : _AST(std::forward<decltype(value)>(value)) {}
    #pragma endregion Constructors
    
    #pragma region Service constructors
    cmp_op(const cmp_op &) = default;
    cmp_op(cmp_op &&) = default;
    cmp_op &operator=(const cmp_op &) = default;
    cmp_op &operator=(cmp_op &&) = default;
    #pragma endregion Service constructors

    #pragma region Destructor
    ~cmp_op() = default;
    #pragma endregion Destructor

    #pragma region Attributes
    
    #pragma endregion Attributes

    #pragma region Extras
    
    #pragma endregion Extras
};


class Eq : _ConcreteASTNode {
public:
    #pragma region Fields
    #pragma endregion Fields

    #pragma region Constructors
    Eq() {};
    #pragma endregion Constructors
    
    #pragma region Service constructors
    Eq(const Eq &) = default;
    Eq(Eq &&) = default;
    Eq &operator=(const Eq &) = default;
    Eq &operator=(Eq &&) = default;
    #pragma endregion Service constructors

    #pragma region Uniform fields access
    /**
     * Returns a tuple of references to all fields.
     * Note that the tuple may include sequences (std::vector) and optional fields (null unique_ptr's).
     */
    auto get_fields_tuple() {
        return std::tie();
    }
    #pragma endregion Uniform fields access

    #pragma region Extras
    
    #pragma endregion Extras
};


class NotEq : _ConcreteASTNode {
public:
    #pragma region Fields
    #pragma endregion Fields

    #pragma region Constructors
    NotEq() {};
    #pragma endregion Constructors
    
    #pragma region Service constructors
    NotEq(const NotEq &) = default;
    NotEq(NotEq &&) = default;
    NotEq &operator=(const NotEq &) = default;
    NotEq &operator=(NotEq &&) = default;
    #pragma endregion Service constructors

    #pragma region Uniform fields access
    /**
     * Returns a tuple of references to all fields.
     * Note that the tuple may include sequences (std::vector) and optional fields (null unique_ptr's).
     */
    auto get_fields_tuple() {
        return std::tie();
    }
    #pragma endregion Uniform fields access

    #pragma region Extras
    
    #pragma endregion Extras
};


class Lt : _ConcreteASTNode {
public:
    #pragma region Fields
    #pragma endregion Fields

    #pragma region Constructors
    Lt() {};
    #pragma endregion Constructors
    
    #pragma region Service constructors
    Lt(const Lt &) = default;
    Lt(Lt &&) = default;
    Lt &operator=(const Lt &) = default;
    Lt &operator=(Lt &&) = default;
    #pragma endregion Service constructors

    #pragma region Uniform fields access
    /**
     * Returns a tuple of references to all fields.
     * Note that the tuple may include sequences (std::vector) and optional fields (null unique_ptr's).
     */
    auto get_fields_tuple() {
        return std::tie();
    }
    #pragma endregion Uniform fields access

    #pragma region Extras
    
    #pragma endregion Extras
};


class LtE : _ConcreteASTNode {
public:
    #pragma region Fields
    #pragma endregion Fields

    #pragma region Constructors
    LtE() {};
    #pragma endregion Constructors
    
    #pragma region Service constructors
    LtE(const LtE &) = default;
    LtE(LtE &&) = default;
    LtE &operator=(const LtE &) = default;
    LtE &operator=(LtE &&) = default;
    #pragma endregion Service constructors

    #pragma region Uniform fields access
    /**
     * Returns a tuple of references to all fields.
     * Note that the tuple may include sequences (std::vector) and optional fields (null unique_ptr's).
     */
    auto get_fields_tuple() {
        return std::tie();
    }
    #pragma endregion Uniform fields access

    #pragma region Extras
    
    #pragma endregion Extras
};


class Gt : _ConcreteASTNode {
public:
    #pragma region Fields
    #pragma endregion Fields

    #pragma region Constructors
    Gt() {};
    #pragma endregion Constructors
    
    #pragma region Service constructors
    Gt(const Gt &) = default;
    Gt(Gt &&) = default;
    Gt &operator=(const Gt &) = default;
    Gt &operator=(Gt &&) = default;
    #pragma endregion Service constructors

    #pragma region Uniform fields access
    /**
     * Returns a tuple of references to all fields.
     * Note that the tuple may include sequences (std::vector) and optional fields (null unique_ptr's).
     */
    auto get_fields_tuple() {
        return std::tie();
    }
    #pragma endregion Uniform fields access

    #pragma region Extras
    
    #pragma endregion Extras
};


class GtE : _ConcreteASTNode {
public:
    #pragma region Fields
    #pragma endregion Fields

    #pragma region Constructors
    GtE() {};
    #pragma endregion Constructors
    
    #pragma region Service constructors
    GtE(const GtE &) = default;
    GtE(GtE &&) = default;
    GtE &operator=(const GtE &) = default;
    GtE &operator=(GtE &&) = default;
    #pragma endregion Service constructors

    #pragma region Uniform fields access
    /**
     * Returns a tuple of references to all fields.
     * Note that the tuple may include sequences (std::vector) and optional fields (null unique_ptr's).
     */
    auto get_fields_tuple() {
        return std::tie();
    }
    #pragma endregion Uniform fields access

    #pragma region Extras
    
    #pragma endregion Extras
};


class In : _ConcreteASTNode {
public:
    #pragma region Fields
    #pragma endregion Fields

    #pragma region Constructors
    In() {};
    #pragma endregion Constructors
    
    #pragma region Service constructors
    In(const In &) = default;
    In(In &&) = default;
    In &operator=(const In &) = default;
    In &operator=(In &&) = default;
    #pragma endregion Service constructors

    #pragma region Uniform fields access
    /**
     * Returns a tuple of references to all fields.
     * Note that the tuple may include sequences (std::vector) and optional fields (null unique_ptr's).
     */
    auto get_fields_tuple() {
        return std::tie();
    }
    #pragma endregion Uniform fields access

    #pragma region Extras
    
    #pragma endregion Extras
};


class NotIn : _ConcreteASTNode {
public:
    #pragma region Fields
    #pragma endregion Fields

    #pragma region Constructors
    NotIn() {};
    #pragma endregion Constructors
    
    #pragma region Service constructors
    NotIn(const NotIn &) = default;
    NotIn(NotIn &&) = default;
    NotIn &operator=(const NotIn &) = default;
    NotIn &operator=(NotIn &&) = default;
    #pragma endregion Service constructors

    #pragma region Uniform fields access
    /**
     * Returns a tuple of references to all fields.
     * Note that the tuple may include sequences (std::vector) and optional fields (null unique_ptr's).
     */
    auto get_fields_tuple() {
        return std::tie();
    }
    #pragma endregion Uniform fields access

    #pragma region Extras
    
    #pragma endregion Extras
};


class attr_op : public _AST<AttrInst, AttrStatic> {
public:
    #pragma region Constructors
    attr_op(auto &&value)
        : _AST(std::forward<decltype(value)>(value)) {}
    #pragma endregion Constructors
    
    #pragma region Service constructors
    attr_op(const attr_op &) = default;
    attr_op(attr_op &&) = default;
    attr_op &operator=(const attr_op &) = default;
    attr_op &operator=(attr_op &&) = default;
    #pragma endregion Service constructors

    #pragma region Destructor
    ~attr_op() = default;
    #pragma endregion Destructor

    #pragma region Attributes
    
    #pragma endregion Attributes

    #pragma region Extras
    
    #pragma endregion Extras
};


class AttrInst : _ConcreteASTNode {
public:
    #pragma region Fields
    #pragma endregion Fields

    #pragma region Constructors
    AttrInst() {};
    #pragma endregion Constructors
    
    #pragma region Service constructors
    AttrInst(const AttrInst &) = default;
    AttrInst(AttrInst &&) = default;
    AttrInst &operator=(const AttrInst &) = default;
    AttrInst &operator=(AttrInst &&) = default;
    #pragma endregion Service constructors

    #pragma region Uniform fields access
    /**
     * Returns a tuple of references to all fields.
     * Note that the tuple may include sequences (std::vector) and optional fields (null unique_ptr's).
     */
    auto get_fields_tuple() {
        return std::tie();
    }
    #pragma endregion Uniform fields access

    #pragma region Extras
    
    #pragma endregion Extras
};


class AttrStatic : _ConcreteASTNode {
public:
    #pragma region Fields
    #pragma endregion Fields

    #pragma region Constructors
    AttrStatic() {};
    #pragma endregion Constructors
    
    #pragma region Service constructors
    AttrStatic(const AttrStatic &) = default;
    AttrStatic(AttrStatic &&) = default;
    AttrStatic &operator=(const AttrStatic &) = default;
    AttrStatic &operator=(AttrStatic &&) = default;
    #pragma endregion Service constructors

    #pragma region Uniform fields access
    /**
     * Returns a tuple of references to all fields.
     * Note that the tuple may include sequences (std::vector) and optional fields (null unique_ptr's).
     */
    auto get_fields_tuple() {
        return std::tie();
    }
    #pragma endregion Uniform fields access

    #pragma region Extras
    
    #pragma endregion Extras
};


class expr_context : public _AST<Load, Store> {
public:
    #pragma region Constructors
    expr_context(auto &&value)
        : _AST(std::forward<decltype(value)>(value)) {}
    #pragma endregion Constructors
    
    #pragma region Service constructors
    expr_context(const expr_context &) = default;
    expr_context(expr_context &&) = default;
    expr_context &operator=(const expr_context &) = default;
    expr_context &operator=(expr_context &&) = default;
    #pragma endregion Service constructors

    #pragma region Destructor
    ~expr_context() = default;
    #pragma endregion Destructor

    #pragma region Attributes
    
    #pragma endregion Attributes

    #pragma region Extras
    
    #pragma endregion Extras
};


class Load : _ConcreteASTNode {
public:
    #pragma region Fields
    #pragma endregion Fields

    #pragma region Constructors
    Load() {};
    #pragma endregion Constructors
    
    #pragma region Service constructors
    Load(const Load &) = default;
    Load(Load &&) = default;
    Load &operator=(const Load &) = default;
    Load &operator=(Load &&) = default;
    #pragma endregion Service constructors

    #pragma region Uniform fields access
    /**
     * Returns a tuple of references to all fields.
     * Note that the tuple may include sequences (std::vector) and optional fields (null unique_ptr's).
     */
    auto get_fields_tuple() {
        return std::tie();
    }
    #pragma endregion Uniform fields access

    #pragma region Extras
    
    #pragma endregion Extras
};


class Store : _ConcreteASTNode {
public:
    #pragma region Fields
    #pragma endregion Fields

    #pragma region Constructors
    Store() {};
    #pragma endregion Constructors
    
    #pragma region Service constructors
    Store(const Store &) = default;
    Store(Store &&) = default;
    Store &operator=(const Store &) = default;
    Store &operator=(Store &&) = default;
    #pragma endregion Service constructors

    #pragma region Uniform fields access
    /**
     * Returns a tuple of references to all fields.
     * Note that the tuple may include sequences (std::vector) and optional fields (null unique_ptr's).
     */
    auto get_fields_tuple() {
        return std::tie();
    }
    #pragma endregion Uniform fields access

    #pragma region Extras
    
    #pragma endregion Extras
};


class arg_defs {
public:
    #pragma region Fields
    sequence<arg_def> args;
    #pragma endregion Fields

    #pragma region Constructors
    arg_defs(sequence<arg_def> args) :
        args{std::move(args)} {}
    #pragma endregion Constructors
    
    #pragma region Service constructors
    arg_defs(const arg_defs &) = delete;
    arg_defs(arg_defs &&) = default;
    arg_defs &operator=(const arg_defs &) = delete;
    arg_defs &operator=(arg_defs &&) = default;
    #pragma endregion Service constructors

    #pragma region Uniform fields access
    /**
     * Returns a tuple of references to all fields.
     * Note that the tuple may include sequences (std::vector) and optional fields (null unique_ptr's).
     */
    auto get_fields_tuple() {
        return std::tie(args);
    }
    #pragma endregion Uniform fields access

    #pragma region Extras
    
    #pragma endregion Extras
};


class arg_def {
public:
    #pragma region Fields
    field<identifier> name;
    field<expr> type;
    #pragma endregion Fields

    #pragma region Constructors
    arg_def(field<identifier> name, field<expr> type) :
        name{std::move(name)}, type{std::move(type)} {}
    #pragma endregion Constructors
    
    #pragma region Service constructors
    arg_def(const arg_def &) = delete;
    arg_def(arg_def &&) = default;
    arg_def &operator=(const arg_def &) = delete;
    arg_def &operator=(arg_def &&) = default;
    #pragma endregion Service constructors

    #pragma region Uniform fields access
    /**
     * Returns a tuple of references to all fields.
     * Note that the tuple may include sequences (std::vector) and optional fields (null unique_ptr's).
     */
    auto get_fields_tuple() {
        return std::tie(name, type);
    }
    #pragma endregion Uniform fields access

    #pragma region Extras
    
    #pragma endregion Extras
};


class call_args {
public:
    #pragma region Fields
    sequence<call_arg> args;
    std::optional<identifier> vararg;
    std::optional<identifier> kwarg;
    #pragma endregion Fields

    #pragma region Constructors
    call_args(sequence<call_arg> args, std::optional<identifier> vararg, std::optional<identifier> kwarg) :
        args{std::move(args)}, vararg{std::move(vararg)}, kwarg{std::move(kwarg)} {}
    #pragma endregion Constructors
    
    #pragma region Service constructors
    call_args(const call_args &) = delete;
    call_args(call_args &&) = default;
    call_args &operator=(const call_args &) = delete;
    call_args &operator=(call_args &&) = default;
    #pragma endregion Service constructors

    #pragma region Uniform fields access
    /**
     * Returns a tuple of references to all fields.
     * Note that the tuple may include sequences (std::vector) and optional fields (null unique_ptr's).
     */
    auto get_fields_tuple() {
        return std::tie(args, vararg, kwarg);
    }
    #pragma endregion Uniform fields access

    #pragma region Extras
    
    #pragma endregion Extras
};


class call_arg {
public:
    #pragma region Fields
    std::optional<identifier> name;
    field<expr> value;
    #pragma endregion Fields

    #pragma region Constructors
    call_arg(std::optional<identifier> name, field<expr> value) :
        name{std::move(name)}, value{std::move(value)} {}
    #pragma endregion Constructors
    
    #pragma region Service constructors
    call_arg(const call_arg &) = delete;
    call_arg(call_arg &&) = default;
    call_arg &operator=(const call_arg &) = delete;
    call_arg &operator=(call_arg &&) = default;
    #pragma endregion Service constructors

    #pragma region Uniform fields access
    /**
     * Returns a tuple of references to all fields.
     * Note that the tuple may include sequences (std::vector) and optional fields (null unique_ptr's).
     */
    auto get_fields_tuple() {
        return std::tie(name, value);
    }
    #pragma endregion Uniform fields access

    #pragma region Extras
    
    #pragma endregion Extras
};


}  // namespace bondrewd::ast::nodes
