// AUTOGENERATED by bondrewd/tools/pegen++/pegenxx.py on 2023-03-11 12:04:23
// DO NOT EDIT

#define BONDREWD_PARSER_IMPL
#include <bondrewd/parse/parser_base.hpp>


namespace bondrewd::parse {


//


}  // namespace bondrewd::parse
