{{ _autogenerated_ }}
#include <bondrewd/parse/parser.gen.hpp>


namespace bondrewd::parse {


#pragma region Rule parsers
{{ generator.gen_rule_parsers(with_impls=True) }}
#pragma endregion Rule parsers


}  // namespace bondrewd::parse
