// NOTE: Unused currently...
{{ _autogenerated_ }}
#pragma once

#include <bondrewd/internal/common.hpp>
#include <bondrewd/parse/parser_base.hpp>


namespace bondrewd::parse {


{%- macro gen_rule_handler(rule) %}

{%- endmacro %}


class Parser : ParserBase<Parser> {
public:

    #pragma region Interface
    {{ root_type }} parse();
    #pragma endregion Interface

protected:
    //
}


}  // namespace bondrewd::parse
